name: Generate Wall Image

on: repository_dispatch

jobs:
  gen_image:
    name: Generate Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install AWS Lambda RIE
        run: |
          mkdir -p ~/.aws-lambda-rie && curl -Lo ~/.aws-lambda-rie/aws-lambda-rie https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie && chmod +x ~/.aws-lambda-rie/aws-lambda-rie
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup Docker Cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile.old') }}
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: docker-image:test
          file: Dockerfile.old
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Run Lambda Function
        run: docker run --platform linux/amd64 -d -v ~/.aws-lambda-rie:/aws-lambda -p 9000:8080 --entrypoint /aws-lambda/aws-lambda-rie docker-image:test /usr/local/bin/npx aws-lambda-ric server.handler
      - name: Call the Lambda Function
        run: |
          curl "http://localhost:9000/2015-03-31/functions/function/invocations" -d '${{ toJson(github.event.client_payload) }}' | jq -r .image | base64 -d > /tmp/wall.jpg
      - name: Commit the Updated image
        run: |
          mv /tmp/wall.jpg generated/wall${{ github.event.client_payload.wallNumber }}.jpg
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -sam "updated image for wall ${{ github.event.client_payload.wallNumber }}"
          git push
